### PR TITLE
Adds starting jed file for ATF1502AS for use with fusecli

### PR DESCRIPTION
**Pull request by RobertBaruch**
Since fusecli requires a jed file to start with, I thought it would be a nice idea to provide a default template jed file that can be used as a starting point. This was generated by creating some minimal logic in WINCUPL, generating the jed file, and then using fusecli to remove that logic and restore the muxes to their default states.

### CODE REVIEW

**Review by whitequark — CHANGES_REQUESTED** [review]
* Please name the file simply `templates/ATF1502AS.jed`
* Please strip the "Created on" comment from the header; perhaps change it to "Blank ATF1502AS fuse map"?
* Not all macrocells have the same configuration. Seems like MC1..MC8, MC9..MC16, and MC17..MC32 have three different configs.
* The GOE and UIM muxes have the entire configuration set to zeroes. The configuration bits of these muxes use a one-hot configuration where only a single fuse is programmed (zero). These bits directly drive pass transistors between the corresponding nets, so you've effectively shorted all pins of the device together. How did you arrive at this configuration?
* Read protection shouldn't be enabled.
* PD pins should be configured for user function.
* PT power shouldn't be on.
* MC power saving mode should be on.
* UES fuses should probably be unprogrammed.

**Comment by whitequark** [comment]
> * How did you arrive at this configuration?

Actually I see that you explained how. This seems like... a *massive* bug in WinCUPL? Like, program this fusemap (carefully), and then measure resistance between basically any two pins, eg M12 and M28. There should be a few hundred ohms between, measured in either polarity.

**Comment by RobertBaruch** [comment]
Well... try this:

```sh
python3 -m util.fusecli -d ATF1502AS riscv-reboot/template.jed set MC24.PT1 UIM7_P
```

That makes all fuses for that PT set to 1, except for one which is set to 0. Now try:

```sh
python3 -m util.fusecli -d ATF1502AS riscv-reboot/template.jed set MC24.PT1 -UIM7_P
```

OK, that sets them all to one. Now try:

```sh
python3 -m util.fusecli -d ATF1502AS riscv-reboot/template.jed set MC24.PT1 GND
```

That sets them all to zero, which is consistent with WinCUPL Is that intended?

**Comment by whitequark** [comment]
Try `get GOE`:
```
GOE6: (00000) (unknown) [16720..16724] invert=(0) on [16754]
GOE5: (00000) (unknown) [16725..16729] invert=(0) on [16755]
GOE4: (00000) (unknown) [16730..16734] invert=(0) on [16756]
GOE3: (00000) (unknown) [16735..16739] invert=(0) on [16757]
GOE2: (00000) (unknown) [16740..16744] invert=(0) on [16758]
GOE1: (00000) (unknown) [16745..16749] invert=(0) on [16759]
```
That's not right.

**Comment by whitequark** [comment]
> Also attaching the WinCUPL-generated JED file [TEST_WINCUPL.zip](https://github.com/whitequark/prjbureau/files/5896987/TEST_WINCUPL.zip)

That file doesn't have the issue I'm talking about:

```
```

**Comment by RobertBaruch** [comment]
Am I not using util.fusecli right? My output doesn't look like yours.

```
$ python3 -m util.fusecli -d ATF1502AS prjbureau/jed_templates/ATF1502AS_template.jed get GOE
GOE6: GND1 invert=off
GOE5: GND1 invert=off
GOE4: GND1 invert=off
GOE3: GND1 invert=off
GOE2: GND1 invert=off
GOE1: GND1 invert=off
```

**Comment by RobertBaruch** [comment]
Also:

```
CFG:
  arming_switch  = armed
  read_protection = off
  jtag_pin_func  = jtag
  pd1_pin_func   = user
  pd2_pin_func   = user
  termination    = bus_keeper
  reset_hysteresis = small
```

So I'm not sure why you're asking that I change the PD pins to user?

**Comment by whitequark** [comment]
> Am I not using util.fusecli right?

Wow, my bad, somehow the file I grabbed from your branch got truncated. Let me edit my review so that it reflects reality.

**Comment by RobertBaruch** [comment]
No worries, take your time, don't feel like this has to be merged quickly.

**Comment by whitequark** [comment]
Updated review.

**Comment by RobertBaruch** [comment]
Done. That still leaves the question of all zeroed fuses for the product terms.

**Comment by whitequark** [comment]
> That still leaves the question of all zeroed fuses for the product terms.

I believe the current configuration is correct, since all `pt_power` fuses are in the `off` state.

**Review by whitequark — COMMENTED** [review]
Could you please do the same for ATF1504AS and ATF1508AS? Then this part of the project will be complete.

**Comment by RobertBaruch** [comment]
Seems like ATF1508AS isn't valid for util.fusecli?

**Comment by whitequark** [comment]
> Seems like ATF1508AS isn't valid for util.fusecli?

Right, we don't have the complete chipdb for it yet, I forgot.

**Comment by RobertBaruch** [comment]
Since I have WinCUPL limping along right now, I could generate some JED files for the 1508, if that helps.

**Comment by whitequark** [comment]
I can do it too (well, I don't use WinCUPL, but I have the fitter running under wine, which is enough) but the problem is that you couldn't reset all macrocells/muxes to a defined state without a chipdb. But we don't have to do it right now.

**Review by whitequark — APPROVED** [review]

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
